"""Revision 7

Revision ID: 8213a005831d
Revises: 7cf54e8c4830
Create Date: 2020-08-25 20:16:05.909835

"""
import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "8213a005831d"
down_revision = "7cf54e8c4830"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    #   op.drop_table("sunspotgroupdata", schema="solardynamo")
    #   op.drop_table("dim_date")
    op.add_column(
        "place_text_search",
        sa.Column("source_entity_id", sa.String(), nullable=True),
        schema="places",
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("place_text_search", "source_entity_id", schema="places")


#   op.create_table(
#       "dim_date",
#       sa.Column("dt", sa.DATE(), autoincrement=False, nullable=True),
#       sa.Column(
#           "yr",
#           sa.INTEGER(),
#           sa.Computed("date_part('year'::text, dt)", persisted=True),
#           autoincrement=False,
#           nullable=True,
#       ),
#       sa.Column(
#           "week",
#           sa.INTEGER(),
#           sa.Computed(
#               "((date_part('DOY'::text, dt))::integer / 7)", persisted=True
#           ),
#           autoincrement=False,
#           nullable=True,
#       ),
#       sa.Column(
#           "isoweek",
#           sa.INTEGER(),
#           sa.Computed("date_part('week'::text, dt)", persisted=True),
#           autoincrement=False,
#           nullable=True,
#       ),
#   )
#   op.create_table(
#       "sunspotgroupdata",
#       sa.Column(
#           "obs_dt_moment",
#           sa.VARCHAR(length=11),
#           autoincrement=False,
#           nullable=True,
#       ),
#       sa.Column("dt", sa.DATE(), autoincrement=False, nullable=True),
#       sa.Column(
#           "obs_moment", sa.INTEGER(), autoincrement=False, nullable=True
#       ),
#       sa.Column(
#           "kislovodsk_ssg", sa.INTEGER(), autoincrement=False, nullable=True
#       ),
#       sa.Column(
#           "latitude",
#           postgresql.DOUBLE_PRECISION(precision=53),
#           autoincrement=False,
#           nullable=True,
#       ),
#       sa.Column(
#           "longitude",
#           postgresql.DOUBLE_PRECISION(precision=53),
#           autoincrement=False,
#           nullable=True,
#       ),
#       sa.Column(
#           "dist_to_center",
#           postgresql.DOUBLE_PRECISION(precision=53),
#           autoincrement=False,
#           nullable=True,
#       ),
#       sa.Column(
#           "obs_ssg_area", sa.INTEGER(), autoincrement=False, nullable=True
#       ),
#       sa.Column(
#           "corr_ssg_area", sa.INTEGER(), autoincrement=False, nullable=True
#       ),
#       sa.Column(
#           "largest_spot_area",
#           sa.INTEGER(),
#           autoincrement=False,
#           nullable=True,
#       ),
#       sa.Column(
#           "quantity", sa.INTEGER(), autoincrement=False, nullable=True
#       ),
#       sa.Column(
#           "meridian_time",
#           sa.VARCHAR(length=20),
#           autoincrement=False,
#           nullable=True,
#       ),
#       schema="solardynamo",
#   )
# ### end Alembic commands ###
